# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 18:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('shuup_simple_cms', '0011_open_graph'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blog_article', models.BooleanField(default=False, help_text='Indicates whether this is a blog article and it should appear on articles list.', verbose_name='This is a blog article')),
                ('image', filer.fields.image.FilerImageField(blank=True, help_text='The image for the article.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_article', to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_article', to='shuup_simple_cms.Page', verbose_name='page')),
            ],
            options={
                'verbose_name': 'blog article',
                'verbose_name_plural': 'blog articles',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlogArticleTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('small_description', models.TextField(blank=True, help_text='Define a small description to be shown in article list. This is the text that should capture users attention.', verbose_name='Small description')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shuup_cms_blog.BlogArticle')),
            ],
            options={
                'verbose_name': 'blog article Translation',
                'db_table': 'shuup_cms_blog_blogarticle_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='blogarticletranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
